name: test
on: [push]
jobs:
  Run-all-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        redis-version: [5]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - run: npm i
      - run: npm test
      - run: touch src/config.env
      - run: echo -e "PORT=5000\nJWT_SECRET=test-secret\nTOKEN_EXPIRATION=360000" > src/config.env
      - run: npm run test:e2e
      - run: ls -a
      - run: cd client && npm i && npm i @testing-library/dom && CI=true npm test
